// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import "time"

type User struct {
	ID                int32
	Name              string
	PhoneNumber       string
	Otp               *string
	OtpExpirationTime *time.Time
}
